//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public string AnswerID { get; set; }
        public string TestID { get; set; }
        public string QuestionID { get; set; }
        public string Username { get; set; }
        public int AttemptNumber { get; set; }
        public int UserAnswer { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual Test Test { get; set; }
        public virtual User User { get; set; }
    }
}
